### ISSUE TITLE
wrong minimum dependency on network-transport

### ISSUE THREAD

**Issue by magnusmorton** [tweag/network-transport-zeromq#24]
The package won't compile with the current minimum dependency on ```network-transport```  - ```Reliability``` is not an instance of ```Binary```; bumping the minimum dependency to ```>=0.4``` fixes it. 

The following was added to ```network-transport``` after 0.3 was released
https://github.com/haskell-distributed/network-transport/commit/44672be03c9d0d66926416fdac23555477f99229

**Comment by mboes** [comment]
close?

**Comment by qnikst** [comment]
t
